languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Jaeung Cheon"
copyright = "Â© 2025 Jaeung Cheon"

[params]
  dateFormat = "2006.01.02"
  # mainSections = ["section1", "section2"]
   description = "Jaeung Cheon's Blog"

[params.author]
  name = "Jaeung Cheon"
  image = "img/author.jpg"
  headline = "Android Software Engineer"
  bio = "Android Software Engineer"
  links = [
    { email = "mailto:cheonjaewoong@gmail.com" },
    { medium = "https://medium.com/@cheonjaeung" },
    { github = "https://github.com/cheonjaeung" },
    { linkedin = "https://linkedin.com/in/cheonjaeung" },
    { instagram = "https://instagram.com/jaeungcheon" },
  ]
